### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by jeremyworger** [joerenner/sampleChop#1]
Hi Joe, what are the steps for running the script?  (for someone who has only used python a couple of times)

**Comment by jeremyworger** [comment]
I downgraded numpy to 1.11.3 (seems only the earlier versions work) 
But now its a different error that im trying to figure out:   
File "C:\Users\Jeremy\Desktop\sampleChop-master\sampleChop\get_data.py", line 19, in <module>
    cqt = np.abs(lb.core.cqt(y, sr=sr, fmin=lb.note_to_hz('F2'),
AttributeError: 'module' object has no attribute 'note_to_hz'

**Comment by joerenner** [comment]
hmm it seems to not be finding this librosa function: https://librosa.org/doc/latest/generated/librosa.note_to_hz.html

I would make sure you have the correct librosa version (0.5.1) installed. 

If you just want to run a song through the system, I would use this function: https://github.com/joerenner/sampleChop/blob/0eac5bf54b55168def11bcb894b43354573402ce/sampleChop/classify.py#L165 just replace the path to the wav or mp3 file.

This library is quite old and I didn't really know what I was doing when I created it... but hopefully it will get some interesting outputs for you!

**Comment by jeremyworger** [comment]
The order to run the program is how you have it written already right? I should run get_data, data_ops, sampleChop, then classify? Or do I just run classify?

**Comment by jeremydeanw** [comment]
I started from scratch and reinstalled everything....it seems that only up to librosa 0.3.1 works. If I try and install 0.5.0 I get the error "exit status 1" (its quite a long error)

**Comment by jeremydeanw** [comment]
Oh! So the issue is installing joblib: https://github.com/librosa/librosa/issues/729   
Woohoo.....now to the next error:  

Please enter audio file name 1.wav
Generating Data
Traceback (most recent call last):
  File "get_data.py", line 20, in <module>
    n_bins=48, hop_length=hop_length, norm=2, real=False))
TypeError: cqt() got an unexpected keyword argument 'real'

**Comment by jeremyworger** [comment]
Ok.....so after alot of scratching my head, I reinstalled everything....and the issue was that I was running 0.3.0 not 0.51. I ran into a bunch of errors, and what fixed it and allowed me to install 0.5.1 was installing llvmlite-0.31.0-cp27-cp27m-win_amd64.whl 
I also needed to fall back joblib per: https://github.com/librosa/librosa/issues/729  

Seems to work now! Running classify.py.
Not sure if its working correctly though...the cuts seem to be random. Not sure what order I'm supposed to go in?
How do I train on multiple drum breaks for instance? 
I have a blank text file in my input folder.....what does the text file do?
Do you have your data points somewhere?  

When running get_data.py on its own I get the error:

File "get_data.py", line 67, in <module>
    truth_times = [float(x) for x in truth_times]
ValueError: could not convert string to float:

**Comment by jeremyworger** [comment]
Would I need to resolve the error above in order to create data points?

**Comment by joerenner** [comment]
Hi Jeremy, 

a couple points: 
- the network checked in was not trained on drum breaks, so this is probably why the cuts seem random.
- if you want to train on your own ground truth cuts, you'll need to write the cut times (in seconds) in the associated wav file to a text file with a comma between each time, then run the get_data script (for each wav/txt file)
- I'm not sure where my data is.

Sorry I can't be more help, this was a side project years ago when I was in school and just messing around getting to know machine learning.

**Comment by jeremyworger** [comment]
Thanks, I'm more just needing to know what the workflow order is....so a temp-plot.html, as well as features + targets txt files were created after running get_data.  I see that in sampleChop.py that it uses these files. 
I tried running sampleChop but ran into an error, I have the seconds as 05,10,15.....is this the correct format?
I'm sure I'll figure it out eventually

ValueError: Found input variables with inconsistent numbers of samples: [251802, 4663] 

(when running sampleChop)
